- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.0.49.0`
> Upgrade to Tomcat 8.0.49

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.5.28.0`
> Upgrade to Tomcat 8.5.28

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=7.0.85.0`
> Upgrade to Tomcat 7.0.85

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.0.50.0`
> Upgrade to Tomcat 8.0.50

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.5.29.0`
> Upgrade to Tomcat 8.5.29

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.5.30.0`
> Upgrade to Tomcat 8.5.30

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.0.52.0`
> Upgrade to Tomcat 8.0.52

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=7.0.88.0`
> Upgrade to Tomcat 7.0.88

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=7.0.90.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.90

- pom.xml
After merging this PR, run `mvn versions:set -DnewVersion=8.0.53.0-SNAPSHOT`
> Upgrade tomcat.version to 8.0.53

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.12.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.12

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.14.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.14

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.37.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.37

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.38.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.38

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.16.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.16

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.93.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.93

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.39.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.39

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.17.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.17

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.94.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.94

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.40.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.40

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.19.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.19

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.41.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.41

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.20.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.20

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.42.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.42

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.21.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.21

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.22.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.22

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.43.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.43

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.96.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.96

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.24.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.24

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.45.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.45

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.26.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.26

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.46.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.46

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.47.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.47

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.27.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.27

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.49.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.49

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.29.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.29

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.50.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.50

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.30.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.30

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.99.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.99

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=9.0.31.0-SNAPSHOT`
> Upgrade tomcat.version to 9.0.31

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.51.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.51

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.100.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.100

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.53.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.53

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=10.0.0-M3.0-SNAPSHOT`
> Upgrade tomcat.version to 10.0.0-M3

- pom.xml
Reverts jkutner/webapp-runner#67
> Revert "Upgrade tomcat.version to 10.0.0-M3"

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=7.0.103.0-SNAPSHOT`
> Upgrade tomcat.version to 7.0.103

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=10.0.0-M4.0-SNAPSHOT`
> Upgrade tomcat.version to 10.0.0-M4

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.54.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.54

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.55.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.55

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.56.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.56

- pom.xml
After merging this PR, run `mvn versions:set -DgenerateBackupPoms=false -DnewVersion=8.5.57.0-SNAPSHOT`
> Upgrade tomcat.version to 8.5.57
